### ISSUE TITLE
Missing site data path in Eleventy config

### ISSUE THREAD

**Issue by camflint** [scottishstoater/eleventy-web-starter#17]
Hi there, thanks for the amazing starter template! I had to change one thing to get it working:

```diff
// .eleventy.js
        dir: {
            input: "src/",
            output: "dist",
            includes: "_includes",
-            layouts: "_layouts"
+            layouts: "_layouts",
+            data: "_data"
        },
```

Without that line, the `src/_data/site.js` global data is not provided to the Nunjuck template environment. For example `site.title`, `site.description`, `site.env` cannot be accessed.

**Comment by chrissy-dev** [comment]
Hey @camflint,

Thanks for taking the time to flag this. 

The data directory in this project is the default Eleventy data directory, that's why it's not defined, it _should_ fallback. 
The default is `_data` and the folder is relative to the input directory, for example: `src/_data`, which is where the folder lives. 
I can run the project without it being defined, what OS are you running 🤔? 

Cheers!

**Comment by chrissy-dev** [comment]
I'm closing this for now @camflint, please feel free to reply and reopen if the issue persists 😃
